# Installation

In [2]:
#!pip install pandas

# reading CSV file

In [3]:
import pandas as pd
import numpy as np



dataFrame = pd.read_csv(r"C:\Users\RAZER\Documents\GitHub_2\CODE_With_SHA\STATS_with_Py\celsius_fahrenheit_lab_data.csv")


dataFrame

Celsius  Fahrenheit
0      -10        13.0
1        0        31.5
2       10        51.2
3       20        70.5
4       30        89.1
5       40       107.2

In [4]:
dataFrame["Celsius"]

0   -10
1     0
2    10
3    20
4    30
5    40
Name: Celsius, dtype: int64

In [5]:
type(dataFrame["Fahrenheit"])

pandas.core.series.Series

In [6]:
dataFrame["Celsius"].values

array([-10,   0,  10,  20,  30,  40])

In [7]:
dataFrame["Fahrenheit"].values

array([ 13. ,  31.5,  51.2,  70.5,  89.1, 107.2])

In [16]:
x = dataFrame["Celsius"].values
y = dataFrame["Fahrenheit"].values



n = len(x)

sum_x = np.sum(x)

sum_y = np.sum(y)

sum_xy = np.sum(x*y)

sum_x2 = np.sum(pow(x,2))


m = (n* sum_xy - sum_x*sum_y) / (n*sum_x2 - pow(sum_x,2))

c = (sum_y- m * sum_x)/n

print("the slope= ",m)
print("the intercept = ",c)


the slope=  1.8945714285714286
the intercept =  31.998095238095235


In [ ]:
cel = 40

far = cel*m + c

print(far)

107.78095238095237


____________________________________________

# With sklearn

In [ ]:
!pip install -U scikit-learn

In [27]:
x

array([-10,   0,  10,  20,  30,  40])

In [28]:
x.reshape(-1,1)

array([[-10],
       [  0],
       [ 10],
       [ 20],
       [ 30],
       [ 40]])

In [ ]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

dataFrame = pd.read_csv(r"C:\Users\RAZER\Documents\GitHub_2\CODE_With_SHA\STATS_with_Py\celsius_fahrenheit_lab_data.csv")


x = dataFrame["Celsius"].values
y = dataFrame["Fahrenheit"].values


#reshaping
x_reshaped = x.reshape(-1,1)


#Model Declaration
lin_model = LinearRegression()


#Training
lin_model.fit(x_reshaped,y)


m_sk = lin_model.coef_[0]
c_sk = lin_model.intercept_


print(m_sk)
print(c_sk)


1.8945714285714284
31.99809523809524


In [ ]:
x_reshaped = x.reshape(-1,1)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Step 1: Load dataset (update the path if needed)
df = pd.read_csv(r"C:\Users\RAZER\Downloads\archive (1)\insurance.csv")  # <-- place your downloaded CSV here

# Step 2: Encode categorical columns
for col in ['sex', 'smoker', 'region']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# Step 3: Define X (features) and y (target: age)
X = df.drop(columns=['age'])
y = df['age']

# Step 4: Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Fit linear regression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Step 6: Evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("✅ Evaluation Results (Actual Age Prediction):")
print(f"MAE : {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²  : {r2:.2f}")


✅ Evaluation Results (Actual Age Prediction):
MAE : 10.00
RMSE: 11.93
R²  : 0.27
